"""add_competency_scores

Revision ID: 1c0053b5e6d6
Revises: 
Create Date: 2026-07-19 14:45:07.896755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models.competency_profile


# revision identifiers, used by Alembic.
revision: str = '1c0053b5e6d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competency_profiles', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('competency_profiles', sa.Column('database_score', sa.Float(), nullable=True))
    op.add_column('competency_profiles', sa.Column('programming_score', sa.Float(), nullable=True))
    op.add_column('competency_profiles', sa.Column('soft_skill_score', sa.Float(), nullable=True))
    op.add_column('competency_profiles', sa.Column('score_explanations', models.competency_profile.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competency_profiles', 'score_explanations')
    op.drop_column('competency_profiles', 'soft_skill_score')
    op.drop_column('competency_profiles', 'programming_score')
    op.drop_column('competency_profiles', 'database_score')
    op.drop_column('competency_profiles', 'overall_score')
    # ### end Alembic commands ###
