"""job_compatibility_engine

Revision ID: 9234ec219496
Revises: 1c0053b5e6d6
Create Date: 2026-07-19 14:52:10.701404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models.competency_profile


# revision identifiers, used by Alembic.
revision: str = '9234ec219496'
down_revision: Union[str, Sequence[str], None] = '1c0053b5e6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_compatibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('best_role', sa.String(), nullable=True),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('matches', models.competency_profile.JSONType(), nullable=True),
    sa.Column('matched_skills', models.competency_profile.JSONType(), nullable=True),
    sa.Column('missing_skills', models.competency_profile.JSONType(), nullable=True),
    sa.Column('recommendation_reason', models.competency_profile.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_compatibility_id'), 'job_compatibility', ['id'], unique=False)
    op.create_index(op.f('ix_job_compatibility_user_id'), 'job_compatibility', ['user_id'], unique=False)
    op.add_column('job_roles', sa.Column('role_name', sa.String(), nullable=True))
    op.add_column('job_roles', sa.Column('preferred_skills', models.competency_profile.JSONType(), nullable=True))
    op.add_column('job_roles', sa.Column('minimum_cgpa', sa.Float(), nullable=True))
    op.add_column('job_roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('job_roles', 'required_skills',
               existing_type=sa.VARCHAR(),
               type_=models.competency_profile.JSONType(),
               existing_nullable=True)
    op.drop_index(op.f('ix_job_roles_title'), table_name='job_roles')
    op.create_index(op.f('ix_job_roles_role_name'), 'job_roles', ['role_name'], unique=True)
    op.drop_column('job_roles', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_roles', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_job_roles_role_name'), table_name='job_roles')
    op.create_index(op.f('ix_job_roles_title'), 'job_roles', ['title'], unique=True)
    op.alter_column('job_roles', 'required_skills',
               existing_type=models.competency_profile.JSONType(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('job_roles', 'created_at')
    op.drop_column('job_roles', 'minimum_cgpa')
    op.drop_column('job_roles', 'preferred_skills')
    op.drop_column('job_roles', 'role_name')
    op.drop_index(op.f('ix_job_compatibility_user_id'), table_name='job_compatibility')
    op.drop_index(op.f('ix_job_compatibility_id'), table_name='job_compatibility')
    op.drop_table('job_compatibility')
    # ### end Alembic commands ###
