"""skill_gap_engine

Revision ID: a0f847298c84
Revises: 9234ec219496
Create Date: 2026-07-19 14:59:51.710076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models.competency_profile


# revision identifiers, used by Alembic.
revision: str = 'a0f847298c84'
down_revision: Union[str, Sequence[str], None] = '9234ec219496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('estimated_duration', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_id'), 'learning_resources', ['id'], unique=False)
    op.create_index(op.f('ix_learning_resources_skill_name'), 'learning_resources', ['skill_name'], unique=False)
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_progress_id'), 'learning_progress', ['id'], unique=False)
    op.create_index(op.f('ix_learning_progress_user_id'), 'learning_progress', ['user_id'], unique=False)
    op.create_table('skill_gap_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('overall_gap_percentage', sa.Float(), nullable=True),
    sa.Column('missing_skills_json', models.competency_profile.JSONType(), nullable=True),
    sa.Column('recommended_resources_json', models.competency_profile.JSONType(), nullable=True),
    sa.Column('action_plan_json', models.competency_profile.JSONType(), nullable=True),
    sa.Column('career_roadmap_json', models.competency_profile.JSONType(), nullable=True),
    sa.Column('career_readiness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_analysis_id'), 'skill_gap_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gap_analysis_user_id'), 'skill_gap_analysis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_gap_analysis_user_id'), table_name='skill_gap_analysis')
    op.drop_index(op.f('ix_skill_gap_analysis_id'), table_name='skill_gap_analysis')
    op.drop_table('skill_gap_analysis')
    op.drop_index(op.f('ix_learning_progress_user_id'), table_name='learning_progress')
    op.drop_index(op.f('ix_learning_progress_id'), table_name='learning_progress')
    op.drop_table('learning_progress')
    op.drop_index(op.f('ix_learning_resources_skill_name'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_id'), table_name='learning_resources')
    op.drop_table('learning_resources')
    # ### end Alembic commands ###
